### ISSUE TITLE
Completed Required Stories 

### ISSUE THREAD

**Issue by gegbo** [Codepath-Final-Project/WatchMe#15]
/cc @codepathreview

**Comment by tuhoag** [comment]
:+1: Great job getting all the required stories done! This is a big milestone as now it's all about adding optionals and additional polish to the app.

There are a few things you must consider:
- Manage tasks with github issues like this repository: https://github.com/QSport/QSport/issues
- It's not a good idea to show pin in your app. You can send the pin to your users via email or phone.
