### ISSUE TITLE
Milestone 3-Submission

### ISSUE THREAD

**Issue by tuhoag** [Codepath-Final-Project/WatchMe#3]
I didn't see your schema. Please make sure you have pushed all your latest project files to your GitHub Repo.

**Comment by gegbo** [comment]
Hello! We are not using a Parse server and are solely using existing APIs
which we documented in our README

**Comment by tuhoag** [comment]
Hi @gegbo, even if you didn't use parse, your application still follows the MVC pattern. So that, you must design your models, which is an Object-Oriented version of your schema.

Please design and push your schema (or models) diagram to your readme.
